export enum HttpErrorType {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  AUTHENTICATION_ADMIN_DENIED = 'ADMIN_PERMISSION_DENIED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
